server:
  port: 80

spring:
  application:
    name: order-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: xxf@1234
#  redis:
#    host: 127.0.0.1
#    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xxf.springcloud.entity       #所有Entity别名类所在包

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #要检索服务
    fetch-registry: true
    service-url:
      #设置与eureka server 交互的地址, 查询服务和注册服务都需要这个地址
      defaultZone: http://${cluser.eureka.ip1}:1001/eureka/

cluser:
  eureka:
    ip1: 127.0.0.1

#注册eureka的密码
security:
  eureka:
     #配置eureka登录的账号
    name: user
    password: CF7hqp*Y