server:
  port: 1001



eureka:
  instance:
    hostname: eureka-server1001
  client:
    #不向注册中心自己
    register-with-eureka: false
    #自己就是注册中，职责就是维护注册实例，不需要检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server 交互的地址, 查询服务和注册服务都需要这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
